name: Build and Deploy to Prod
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build Frontend
        run: cd frontend && npm install && npm run build
      - name: Copy Static Build
        run: cd .. && cp -r ./frontend/build/ ./build/
      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to App Engine
        run: gcloud app deploy --project=${{ secrets.GCP_PROJECT }} --quiet
